name: rag-evaluation1
version: '1.0'

services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ../docker/sql.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rag_evaluation

    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  backend:
    build: 
      context: ../rag-evaluation-backend
      dockerfile: Dockerfile
    volumes:
      - ../rag-evaluation-backend:/app
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/rag_evaluation
      - POSTGRES_SERVER=db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      
  frontend:
    build:
      context: ../rag-evaluation-frontend
      dockerfile: Dockerfile
    volumes:
      - ../rag-evaluation-frontend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data: